/**
 * Hook that generates an opt-in daily AI brief from non-content email counts.
 *
 * Streams the response for a typing effect and caches the result per user/day.
 * It never starts work unless the caller explicitly enables it.
 */

import { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useOxy } from '@oxy.so/services';
import { inboxLocalDayWindow, streamInboxDailyBrief } from '@/services/inboxInferenceApi';

const BRIEF_CACHE_TTL = 30 * 60 * 1000; // 30 minutes

export interface UseDailyBriefOptions {
  /** When false, the hook does no work — used to honor the `aiBrief` pref. */
  enabled?: boolean;
  /** Only generate after the caller has opened the collapsed brief. */
  autoGenerate?: boolean;
}

export function useDailyBrief(options: UseDailyBriefOptions = {}) {
  const { enabled = true, autoGenerate = false } = options;
  const queryClient = useQueryClient();
  const { oxyServices, user } = useOxy();

  // The API receives the exact UTC instants bounding the user's local calendar
  // day. This remains correct across 23/25-hour daylight-saving transitions.
  const { day, startAt, endAt } = inboxLocalDayWindow();
  const userId = user?.id ?? null;
  // Briefs contain private account-derived counts, so a same-day account
  // switch must never reuse another account's cache entry.
  const cacheKey = useMemo(
    () => ['daily-brief', userId, day] as const,
    [day, userId],
  );
  const generationKey = userId ? `${userId}:${day}` : null;

  const [briefState, setBriefState] = useState<{ scope: string | null; text: string }>(() => ({
    scope: generationKey,
    text: queryClient.getQueryData<string>(cacheKey) ?? '',
  }));
  const runControllerRef = useRef<AbortController | null>(null);
  const unmountedRef = useRef(false);
  const autoGeneratedForRef = useRef<string | null>(null);
  const pendingFrameRef = useRef<number | null>(null);

  // Cancel work before an automatic generation effect can run. This ordering
  // also keeps Strict Mode's mount cycle deterministic.
  useEffect(() => {
    unmountedRef.current = false;
    return () => {
      unmountedRef.current = true;
      runControllerRef.current?.abort();
      if (pendingFrameRef.current !== null) {
        cancelAnimationFrame(pendingFrameRef.current);
        pendingFrameRef.current = null;
      }
    };
  }, []);

  // Account and day changes are new generation scopes. Abort an old stream so
  // it cannot finish into the newly selected account's mounted component.
  useEffect(() => {
    autoGeneratedForRef.current = null;
    runControllerRef.current?.abort();
  }, [day, userId]);

  // Closing the brief should also stop an in-flight request. Reopening it is a
  // deliberate new opt-in and may make one fresh attempt for this user/day.
  useEffect(() => {
    if (enabled) return;
    autoGeneratedForRef.current = null;
    runControllerRef.current?.abort();
  }, [enabled]);

  // Read a cached result during render for an already-completed day. Streamed
  // text remains scoped locally, so a user switch cannot flash old content.
  const cachedBrief = enabled ? queryClient.getQueryData<string>(cacheKey) : undefined;
  const briefText = !enabled
    ? ''
    : briefState.scope === generationKey
      ? briefState.text || cachedBrief || ''
      : cachedBrief || '';

  const generateMutation = useMutation<string, Error, void>({
    mutationKey: cacheKey,
    retry: false,
    mutationFn: async () => {
      const controller = new AbortController();
      if (unmountedRef.current) controller.abort();
      runControllerRef.current?.abort();
      runControllerRef.current = controller;

      let accumulated = '';

      try {
        for await (const delta of streamInboxDailyBrief(
          oxyServices.httpService,
          { startAt, endAt },
          controller.signal,
        )) {
          accumulated += delta;
          // Commit at most once per frame so the list header is not remeasured
          // once per streamed token.
          if (pendingFrameRef.current === null) {
            pendingFrameRef.current = requestAnimationFrame(() => {
              pendingFrameRef.current = null;
              if (!unmountedRef.current) setBriefState({ scope: generationKey, text: accumulated });
            });
          }
        }

        if (pendingFrameRef.current !== null) {
          cancelAnimationFrame(pendingFrameRef.current);
          pendingFrameRef.current = null;
        }
        if (!accumulated) throw new Error('Inbox AI returned an empty brief');
        if (!unmountedRef.current) setBriefState({ scope: generationKey, text: accumulated });

        queryClient.setQueryDefaults(cacheKey, {
          staleTime: BRIEF_CACHE_TTL,
          gcTime: BRIEF_CACHE_TTL,
        });
        queryClient.setQueryData(cacheKey, accumulated, { updatedAt: Date.now() });

        return accumulated;
      } catch (error) {
        if (pendingFrameRef.current !== null) {
          cancelAnimationFrame(pendingFrameRef.current);
          pendingFrameRef.current = null;
        }
        // A truncated or rejected stream is not a valid brief. Do not leave
        // partial model output looking like a completed account summary.
        if (!unmountedRef.current) setBriefState({ scope: generationKey, text: '' });
        throw error;
      } finally {
        if (runControllerRef.current === controller) runControllerRef.current = null;
      }
    },
  });

  const { mutate: runGenerate, isPending } = generateMutation;

  const generate = useCallback((): boolean => {
    if (!enabled || !userId || isPending) return false;

    const cached = queryClient.getQueryData<string>(cacheKey);
    if (cached) {
      setBriefState({ scope: generationKey, text: cached });
      return true;
    }

    setBriefState({ scope: generationKey, text: '' });
    runGenerate();
    return true;
  }, [cacheKey, enabled, generationKey, isPending, queryClient, runGenerate, userId]);

  // A caller may opt into one automatic attempt after opening the brief. The
  // user/day guard prevents pagination and refetches from starting another.
  useEffect(() => {
    if (!autoGenerate || !enabled || !generationKey) return;
    if (autoGeneratedForRef.current === generationKey) return;
    if (generate()) autoGeneratedForRef.current = generationKey;
  }, [autoGenerate, enabled, generate, generationKey]);

  const regenerate = useCallback(() => {
    queryClient.removeQueries({ queryKey: cacheKey });
    autoGeneratedForRef.current = generationKey;
    setBriefState({ scope: generationKey, text: '' });
    generate();
  }, [cacheKey, generate, generationKey, queryClient]);

  return {
    briefText,
    isStreaming: generateMutation.isPending,
    isLoading: generateMutation.isPending && briefText.length === 0,
    error: generateMutation.error,
    generate,
    regenerate,
  };
}
